define(function () {
    var logos = [{
        id: 1,
        src: 'images/icons/anchor29.svg'
    }, {
        id: 2,
        src: 'images/icons/bird39.svg'
    }, {
        id: 3,
        src: 'images/icons/birds27.svg'
    }, {
        id: 4,
        src: 'images/icons/butterfly22.svg'
    }, {
        id: 5,
        src: 'images/icons/caduceus5.svg'
    }, {
        id: 6,
        src: 'images/icons/cubes1.svg'
    }, {
        id: 7,
        src: 'images/icons/deer4.svg'
    }, {
        id: 8,
        src: 'images/icons/dog50.svg'
    }, {
        id: 9,
        src: 'images/icons/favorite21.svg'
    }, {
        id: 10,
        src: 'images/icons/feather29.svg'
    }, {
        id: 11,
        src: 'images/icons/gecko1.svg'
    }, {
        id: 12,
        src: 'images/icons/globe16.svg'
    }, {
        id: 13,
        src: 'images/icons/headphones20.svg'
    }, {
        id: 14,
        src: 'images/icons/horse125.svg'
    }, {
        id: 15,
        src: 'images/icons/infinite3.svg'
    }, {
        id: 16,
        src: 'images/icons/leo5.svg'
    }, {
        id: 17,
        src: 'images/icons/libra4.svg'
    }, {
        id: 18,
        src: 'images/icons/lightning46.svg'
    }, {
        id: 19,
        src: 'images/icons/love148.svg'
    }, {
        id: 20,
        src: 'images/icons/pisces5.svg'
    }, {
        id: 21,
        src: 'images/icons/print48.svg'
    }, {
        id: 22,
        src: 'images/icons/quaver11.svg'
    }, {
        id: 23,
        src: 'images/icons/rabbit5.svg'
    }, {
        id: 24,
        src: 'images/icons/sagittarius6.svg'
    }, {
        id: 25,
        src: 'images/icons/sea-life12.svg'
    }, {
        id: 26,
        src: 'images/icons/sun61.svg'
    }, {
        id: 27,
        src: 'images/icons/tarantula.svg'
    }, {
        id: 28,
        src: 'images/icons/theater3.svg'
    }, {
        id: 29,
        src: 'images/icons/tool114.svg'
    }, {
        id: 30,
        src: 'images/icons/world91.svg'
    }, {
        id: 31,
        src: 'images/icons/cloud-storage5.svg'
    }, {
        id: 32,
        src: 'images/icons/cocktail32.svg'
    }, {
        id: 33,
        src: 'images/icons/flame1.svg'
    }, {
        id: 34,
        src: 'images/icons/molecule17.svg'
    }, {
        id: 35,
        src: 'images/icons/romantic5.svg'
    }, {
        id: 36,
        src: 'images/icons/sprig2.svg'
    }];

    return logos;
});